export class Data {
      constructor(
          public object_id,
          public term_taxonomy_id,
          public term_order,
          public ID,
          public post_author,
          public post_date,
          public post_date_gmt,
          public post_content,
          public post_title,
          public post_excerpt,
          public post_status,
          public post_comment_status,
          public comment_status,
          public comment_count,
          public ping_status,
          public post_password,
          public post_name,
          public to_ping,
          public pinged,
          public post_modified,
          public post_modified_gmt,
          public post_content_filtered,
          public post_parent,
          public guid,
          public menu_order,
          public post_type,
          public post_mine_type,
          public meta_value,
          public post_id,
          public meta_key
  
    ){}
  }